### ISSUE TITLE
Support docks in Leo's core

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1150]
This issue is a revision of #777.  It is independent of #1093: add pyzo features to Leo.

Started May 5, 2019. Code complete and debugged on May 30.

**Status**

- [x] The --dock command-line argument enables QDockWidgets.
- [x] Use QDockWidgets in Leo's top-level DynamicWindow class, a subclass of QMainWindow.
- [x] Put the outline and body panes in separate QDockWidgets.
- [x] The toggle-split-direction command just issues a warning when --dock is in effect.
- [x] Add convenience method, dw.createDockWidget.
- [x] Save/restore dock layout. 
- [x] Put each additional body pane in a separate QDockWidget. This *is* worth doing.
- [x] Make the components of the Tabs dock dockable.
    **legacy_log_dock switch** in qt_frame.py:
    - True: the Spell & Find tabs remain in the Tabs dock. 
    - False: Use separate docks for the Spell & Find tabs.
    For now, I'm leaning towards using docks whenever possible.
- [x] Add dock-related css to all Leo theme files.  See below.

#1154 (Support g.app.dock in plugins) is now a separate issue so I can close this issue.
 
**Bugs**

- [x] Leo doesn't preserve the sizes of the main window properly. Fixed at 8119f8.
- [x] Problems saving/restoring dock positions with multiple outlines.
- [x] Tab completion doesn't ensure that the Tab dock is visible.
 Fixed elegantly at 18af67e using QWidget.raise_.
- [x] **Deferred**: I'll fix these (use QWidget.raise_?) only if we decide to allow floatable docks.
The following are actually the same bug.
 - Alt-x doesn't set focus properly when the body pane is free-floating.
 - After selecting a word in the body editor, Ctrl-f doesn't change the focus to the spell tab.
 The selection is transferred to the search field but the focus remains in the body tab.
- [x] Tab layout not correct in second outline. Fixed at 99cc3c9.
 Leo saves/restores per-outline dock state *only*, defaulting to a global state if necessary.
- #1159: Raise dock widgets as needed.

**css**

Here are the new entries in EKRWindowsDark.leo:
```css
QMainWindow::separator {
    /* The separator between QDockWidget's. */
    background: @dark-base01;
    width: 4px; height: 4px;
    border: 2px solid black;
}
QDockWidget::title {
    color: @dark-base3;
    background: black;
    border: 1px solid @dark-base2;
}
QDockWidget::close-button, QDockWidget::float-button {
    background: @solarized-base01;
}
QLineEdit#editorLabel {
    border: 1px solid @dark-base2;
}
```
**Qt Styles**

Leo does not use Qt styles, and does not need to. [pyzo issue #566](https://github.com/flexxui/flexx/issues/566) arose from confusion between Cleanlooks and Fusion styles.  Alas, the cool Cleanlooks splitter "grip" is  [C++ code](https://github.com/qt/qtstyleplugins/blob/master/src/plugins/styles/cleanlooks/qcleanlooksstyle.cpp), so it can not easily be made part of Leo.
