### ISSUE TITLE
vim-mode-*-border settings do not work on Qt 5

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1221]
See [this post](https://groups.google.com/d/msg/leo-editor/jarOLhwAazY/wWdgVwmUAQAJ) for a discussion.

**The problem**

The three vim-mode-*-border settings in the default stylesheet in leoSettings.leo are affected by a known Qt bug. Class selectors do not work on Qt 5!  Worse, they ruin all later css elements!

These toxic class selectors all reside in the last node: `zz Must be last`. The vim-related items are:
```css
/* Vim mode borders... */
QTextEdit#richTextEdit[vim_state~="vim_normal"] {
  border: @vim-mode-normal-border;
}
QTextEdit#richTextEdit[vim_state~="vim_insert"] {
  border: @vim-mode-insert-border;
}
QTextEdit#richTextEdit[vim_state~="vim_visual"] {
  border: @vim-mode-visual-border;
}
```
**The fixes**

- [x]  vc.set_property uses settings instead of css classes.
- [x] Update leoSettings.leo.
- [x] Update all Theme files.

**New settings**

Defaults as shown:
```
@string vim-mode-normal-border = border: 3px solid white
@string vim-mode-insert-border = border: 3px solid red
@string vim-mode-visual-border = border: 3px solid gray
@string vim-mode-unfocused-border = border: 3px dashed white
```
