### ISSUE TITLE
Use labels instead of buttons in the Find Tab

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1342]
This is a workaround for #1337, which can't be fixed directly because pressing a button changes focus.

**Status**

- Completed at rev 8aaa9b8 in the find-tab branch.
- I'll await user comments before merging into devel.

All converted labels have find-label as their Qt object name.  I use the following style sheet entry for my personal dark theme.
```css
QLabel#find-label {
  color: @dark-base1;
  border: 1px solid white;
  padding: 1px;
}
```
