### ISSUE TITLE
theme font-size-tree takes no effect

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1783]
It is so strange that font-size-tree takes no effect in **EKRLight.leo**. But `font-size-log` and `font-size-body ` are ok.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/2628013/102064293-1665f680-3e32-11eb-9c77-8476ee84332e.png">

***

But in **EKRDark.leo**,  font-size-tree is OK.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/2628013/102064506-588f3800-3e32-11eb-90aa-49176180a55a.png">

I can not find the reason. Any one can help me? Thanks

**Comment by wangzhaohe** [comment]
The following are *.leo files which I used:

+ EKRDark_use.leo
+ EKRLight_use.leo
+ myLeoSettings.leo

Download form net:

[https://pan.baidu.com/s/1SFL5rlIJXuGp_MlQ9b8QiQ](https://pan.baidu.com/s/1SFL5rlIJXuGp_MlQ9b8QiQ)

password: dae9

**Comment by edreamleo** [comment]
It works for me on Windows. Perhaps this is a MacOS problem.

Leo's show-style-sheet command will show you the actual stylesheet in effect. 

Here is the default portion of the stylesheet for the tree
```css
/* ----- QTreeView: base class for QTreeWidget ----- */
QTreeView {
/* These apply to the selected item, but not to editing items.*/
color: #eee8d5;
font-family: DejaVu Sans Mono;
font-size: 16pt;
font-weight: normal; /* normal,bold,100,..,900 */
font-style: normal; /* normal, italic,oblique */
show-decoration-selected: 1; /* Extend the selection */
}
```
