### ISSUE TITLE
Improve focus-border handling in qt stylesheet

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#183]
[Original post](https://groups.google.com/forum/#!topic/leo-editor/9AO-djbRTiw)

I plan to make this part of leoSettings.leo early in the Leo 5.2 release cycle.  The tweaks discussed below seem a bit much to put into 5.1-final.  

Here is the present text of the ``@data qt-gui-user-style-sheet`` node in myLeoSettings.leo. 

```css
/* alternative active pane highlighting */
QTextEdit#log-widget,
QLineEdit#lineEdit,
QScrollArea#findScrollArea,
LeoQTreeWidget#treeWidget,
QTextEdit#richTextEdit {
    border-color: @focused-border-unfocus-color;
    border-style: @focused-border-style;
    border-width: @focused-border-width;
}
QTextEdit:focus#log-widget,
QLineEdit:focus#lineEdit,
QScrollArea:focus#findScrollArea,
LeoQTreeWidget:focus#treeWidget,
QTextEdit:focus#richTextEdit {
    border-color: @focused-border-focus-color;
}
QLineEdit#findPattern, QLineEdit#findChange {
    border-color: black;    /* was: focused-border-unfocus-color; */
    border-style: @focused-border-style;
    border-width: 1;        /* was focused-border-width; */
}
QLineEdit:focus#findPattern, QLineEdit:focus#findChange {
    border-color: @focused-border-focus-color;
    border-style: @focused-border-style;
    border-width: @focused-border-width;
}
QTextEdit:hover#log-widget, LeoQTreeWidget:hover#treeWidget,
QTextEdit:hover#richTextEdit {
}
```
The only change from John's suggestion is separate handling of the ``QLineEdit:focus#findPattern`` and ``QLineEdit:focus#findChange`` selectors.  As you can see, the unselected values for color and width are ``black`` and ``1``.  This shows the frame around the text box as usual.  Of course, these can be modified as you will.

**Additional complications**

1. It's reasonable to use John's unmodified css when ``@bool minibuffer_find_mode = True`` is in effect.  In that case, the ``QLineEdit:focus#findPattern`` and ``QLineEdit:focus#findChange`` selectors are pretty much moot because the find/change text box will rarely have focus.

2. When playing with css containing @ values, you **must not** try to comment out the @ values. The reason is that the @ values almost always contain css comments in their definition and *css comments do not nest*! That's why the above says:

```css
QLineEdit#findPattern, QLineEdit#findChange {
    border-color: black;    /* was: focused-border-unfocus-color; */
    border-style: @focused-border-style;
    border-width: 1;        /* was focused-border-width; */
}
```
instead of:
```css
QLineEdit#findPattern, QLineEdit#findChange {
    border-color: black;    /* was: @focused-border-unfocus-color; */
    border-style: @focused-border-style;
    border-width: 1;        /* was @focused-border-width; */
}
```
Do you see the difference?  It is important!
